### ISSUE TITLE
It seems hw5 has a little "problem"

### ISSUE THREAD

**Issue by hitdshu** [MARMOTatZJU/GAMES101-HW#1]
Hi Marmotat,

Thanks for your sharing of your hw solutions. However, it seems in hw5, you don't multiply the x/y by 2. And as a result, your true fov is not the designed fov.

x = (float)x / scene.width - 0.5;
x *= 2 * scale * imageAspectRatio; // You lost 2 here
y = (float)y / scene.height - 0.5;
y *= 2 * scale; // You lost 2 here

**Comment by MARMOTatZJU** [comment]
You are right. Thank you a lot for point it out. 
It was true that I had been facing something weird wit FoV at that time.
