### ISSUE TITLE
Solve "over-exposed" problem in hw7

### ISSUE THREAD

**Issue by undersilence** [MARMOTatZJU/GAMES101-HW#2]
in Scene.cpp:128 and :130, you divide **RussianRoulette** twice, it will brighten the image.

**Comment by MARMOTatZJU** [comment]
Thank you very much for your advice!

**Comment by MARMOTatZJU** [comment]
Fixed in commit https://github.com/MARMOTatZJU/GAMES101-HW/commit/b53fe6407b8e4ced48034e6b5a922408bbae6075, thank you again!
