### ISSUE TITLE
冒昧的问一句，请问这个是被批改过的作业吗

### ISSUE THREAD

**Issue by dingyalei** [MARMOTatZJU/GAMES101-HW#3]
RT

**Comment by MARMOTatZJU** [comment]
是的，我参与了GAMES101第一期课程。

**Comment by yongbaoXu** [comment]
请问，计算x和y的坐标时，
 y = (float) (scene.height-1 - j) / scene.height - 0.5;
 y值的公式为什么不是
 y = (float) j / scene.height - 0.5;
呢？有些不懂~
谢谢~

**Comment by MARMOTatZJU** [comment]
> 请问，计算x和y的坐标时，
> y = (float) (scene.height-1 - j) / scene.height - 0.5;
> y值的公式为什么不是
> y = (float) j / scene.height - 0.5;
> 呢？有些不懂~
> 谢谢~

因为y轴方向是从下到上，j轴方向是从上到下。
